### ISSUE TITLE
[BUG] Windows上关闭窗口后再从任务栏打开响应非常慢

### ISSUE THREAD

**Issue by TonyBlur** [wonfen/clash-verge-rev#12]
**Describe the bug**
Windows上关闭窗口后再从任务栏打开响应非常慢，基本是5秒左右

**To Reproduce**
每次从任务栏打开都是

**Expected behavior**
希望能优化打开窗口的速度，即点即开

**Information**

- OS: Windows
- Clash Verge Version: 1.4.0
- Clash Core: Clash Meta

**Comment by wonfen** [comment]
检查下你自己电脑的问题。没有其他人反馈过这个问题。

**Comment by TonyBlur** [comment]
> 检查下你自己电脑的问题。没有其他人反馈过这个问题。

好的，我近期会换一台性能更好的电脑重新测试。不过我之前尝试重新安装过，但是并没有解决这个问题。我也也使用过cfw，cfw也没有遇到此类问题。

**Comment by wonfen** [comment]
尝试卸载再重新安装下webview2

**Comment by TonyBlur** [comment]
> 尝试卸载再重新安装下webview2

好的谢谢，我重新安装，测试其他电脑后发现没有那么慢了，但是仍然比cfw慢一点
