### ISSUE TITLE
[BUG]UI界面显示不正常！

### ISSUE THREAD

**Issue by wei727** [wonfen/clash-verge-rev#15]
![截图20231126143752](https://github.com/wonfen/clash-verge-rev/assets/81148177/d1e7061d-6d1a-45a7-937d-3e18302630f9)
哪位大佬知道这是怎么回事啊，之前都没这情况突然一天打开软件UI界面就成这样了。。。。

**Comment by wonfen** [comment]
重新安装下webview2试试。

**Comment by wei727** [comment]
> 重新安装下webview2试试。
 感谢你的解答，问题得到解决！
