### ISSUE TITLE
Add Linux arm64 aarch64 support!

### ISSUE THREAD

**Issue by Tesoro1116** [wonfen/clash-verge-rev#19]
I have some server and Raspberry Pi running with ARM chips.
Clash Meta core have armv8 arm64 support.

**Comment by wonfen** [comment]
Does Raspberry Pi and arm servers need UI?

**Comment by haai-team** [comment]
I also have a raspberry pi 4b.
I tried to install clash-verge_1.4.9_arm64.deb, faild.
Hope can add armhf support, many many thanks!

pi@rasp4b:~/Desktop $ uname -a
Linux rasp4b 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

pi@rasp4b:~/Desktop $ sudo dpkg -i ./clash-verge_1.4.9_arm64.deb 
dpkg: 处理归档 ./clash-verge_1.4.9_arm64.deb (--install)时出错：
 软件包体系结构(arm64)与本机系统体系结构(armhf)不符
在处理时有错误发生：
 ./clash-verge_1.4.9_arm64.deb

**Comment by haai-team** [comment]
OS info:
pi@rasp4b:~/Desktop $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"

**Comment by MystiPanda** [comment]
报错说的不够清楚吗？
