### ISSUE TITLE
[Feature] Support Homebrew install method

### ISSUE THREAD

**Issue by Mrered** [wonfen/clash-verge-rev#23]
**Is your feature request related to a problem? Please describe.**
As the title.

**Describe the solution you'd like**
I have already implemented this feature.

**Describe alternatives you've considered**
No.

**Additional context**

⚠️⚠️⚠️ **This app is conflict with [`clash-verge`](https://github.com/zzzgydi/clash-verge), so you must uninstall `clash-verge` at first.** ⚠️⚠️⚠️

To install this app via Homebrew:

```sh
brew tap ivaquero/chinese
brew update
brew install --cask clash-verge-rev
```

**Comment by wonfen** [comment]
等我研究一下。

**Comment by Mrered** [comment]
你不用研究了，我已经搞定力！你直接搬过去用就好力！（狗头

**Comment by ansemz** [comment]
> 你不用研究了，我已经搞定力！你直接搬过去用就好力！（狗头

感谢

**Comment by Mrered** [comment]
这个东西你可以不用搬过去，我和其他几个小伙伴一直会维护的，直接用就好了。要想自己研究，可以花点时间学一下：

> [官方参考文档](https://docs.brew.sh/Cask-Cookbook)
