### ISSUE TITLE
[Feature]链式代理可以支持wireguard作为出口吗

### ISSUE THREAD

**Issue by hack11112** [wonfen/clash-verge-rev#26]
单独使用wireguard时候是没问题的，但是使用wireguard作为relay代理类型的出口时就会出问题

**Comment by lilyblessing** [comment]
> wireguard目前不支持在relay中使用。如果需要，请使用 proxy 中的 dialer-proxy 配置项

请查阅文档对应部分 https://wiki.metacubex.one/config/proxy-groups/relay/

**Comment by lilyblessing** [comment]
> 了解，有考虑集成到relay里吗，感觉这个更方便点

这不是GUI问题，请去内核反馈
