### ISSUE TITLE
应用目录可以转移位置吗

### ISSUE THREAD

**Issue by monsoon585** [wonfen/clash-verge-rev#28]
用的是portable版本，但是应用目录自动建在了C:\Users\XXX\.config下面，可以把这个目录转移到内核目录一起吗？

**Comment by yueliuLEE** [comment]
在内核目录下新建一个.config\PORTABLE文件夹就可以了

**Comment by monsoon585** [comment]
> 在内核目录下新建一个.config\PORTABLE文件夹就可以了

成功了！谢谢！
