### ISSUE TITLE
[BUG] 使用这个节点启动荒野大嫖客2，r星服务器登录不上去

### ISSUE THREAD

**Issue by hack11112** [wonfen/clash-verge-rev#30]
想问下是节点的问题还是什么的问题，我也不太清楚。还是必须使用加速器

**Comment by RJSackville** [comment]
用的系统代理模式？在连接里面有没有看到R星启动器的进程相关的连接？
还有试没试过TUN模式，没有的话在设置里面打开服务模式和TUN模式再看看。他可能默认不会走系统代理，你要想用代理得打开TUN模式

**Comment by wonfen** [comment]
用管理员模式运行verge可以不用开服务模式
