### ISSUE TITLE
原来CFW里正常使用的yaml配置文件，无法导入

### ISSUE THREAD

**Issue by flingbird122** [wonfen/clash-verge-rev#32]
在导入yaml文件时报错。。。。
一直在CFW正常使用和更新啊

![01](https://github.com/wonfen/clash-verge-rev/assets/88576440/804998e4-bd7d-4d65-9382-792f8ce257f3)

**Comment by wonfen** [comment]
这个提示是你机场配置文件的网站证书有问题。
