### ISSUE TITLE
[Feature] 过滤条件建议

### ISSUE THREAD

**Issue by sagasm** [wonfen/clash-verge-rev#4]
1. 目前连接页面按 Host 过滤,能否另外加三个输入框,分别过滤 Chains Rule 和 Process.
2. 类似地, 规则页面能否添加 一个 Group过滤.

**Comment by Kuingsmile** [comment]
> 1. 目前连接页面按 Host 过滤,能否另外加三个输入框,分别过滤 Chains Rule 和 Process.
> 2. 类似地, 规则页面能否添加 一个 Group过滤.

连接页面 每个类型的表头处鼠标停留时，三个点的悬浮按钮可以点开，里面的filter就是对这个类型进行过滤 不止Chanins Ruls啥的，所有类型都可以单独过滤

![image](https://github.com/wonfen/clash-verge-rev/assets/96409857/2765faa2-c4b9-4216-b192-282b0cfa86f9)

**Comment by sagasm** [comment]
看到了,谢谢
