### ISSUE TITLE
[BUG] MacOS 14.1.1 M1 无法正常开启Tun实现全局代理

### ISSUE THREAD

**Issue by yuhaya** [wonfen/clash-verge-rev#9]
**Describe the bug**
11-24 21:22:27WARNING
[TUN] default interface changed by monitor, => en1
11-24 21:22:27ERROR
Start TUN listening error: configure tun interface: Connect: operation not permitted

**Screenshots**
<img width="912" alt="截屏2023-11-24 21 24 52" src="https://github.com/wonfen/clash-verge-rev/assets/2966240/d68b506e-5c38-419b-81cb-e45693f17199">

**Information**

- OS: [e.g. macOS]
- Clash Verge Version: [1.4.0]
- Clash Core: [e.g. Clash or Clash Meta]

**Comment by wonfen** [comment]
设置下面点“Clash内核”⚙️，然后点🔒，解锁权限。
